// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWN1YdqfYwnND5w0FD7iMFcjdqCuyiu8',
    appId: '1:733899787017:android:80b04e7ffefe38782561d8',
    messagingSenderId: '733899787017',
    projectId: 'estrondo-381713',
    storageBucket: 'estrondo-381713.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9IsZk_fWq0_t73qV9wcoHyhMPHfyukM',
    appId: '1:733899787017:ios:d95858621694a19a2561d8',
    messagingSenderId: '733899787017',
    projectId: 'estrondo-381713',
    storageBucket: 'estrondo-381713.firebasestorage.app',
    androidClientId: '733899787017-8rr9etv8bremcnni9olpcv9squq3hsfl.apps.googleusercontent.com',
    iosClientId: '733899787017-cvm5o2e0rokfo0ouu5bfvdrba8mokpqb.apps.googleusercontent.com',
    iosBundleId: 'one.estrondo.tremors',
  );

}